set up environment
tacettinkustu/Microverse-Review-Project pull request #1
Opened 2021-06-02 09:52 UTC by tacettinkustu

set up environment for review

2021-06-02 10:08 UTC, tacettinkustu commented
## Hello @tacettinkustu ✋, 

You did a good job so far! However, there are few changes you need to make so that you can move on to the next project but don't worry you are almost there.

## Required Changes ♻️

- [ ] Please leverage your README file 
- [ ] You may delete all of unnecessary lines in your .gitignore file

_ And check the comments under the review._

### Cheers and Keep Rocking!👏👏👏

Feel free to leave a question, or a comment on the PR thread if something is not clear 100%

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-02 10:13 UTC, tacettinkustu commented on index.html
>      <div id="img-div">
It would be nicer if you can use semantic HTML elements

2021-06-02 17:04 UTC, acushlakoncept requested changes
Hi @tacettinkustu,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
Your CR is well organized, I like it.

## Required Changes ♻️
_Check the comments under the review._

It's super important that we always state the reasons we want students to make a certain change because it gives them more insights on why your requested change is a better approach.

"Please leverage your README file", I think this could be a bit confusing to some student, instead let's try to break down further like, "I think you should add a ReadMe file to your project since it gives people first-hand information about your project when the visit your repo ...."

About deleting all lines in your `.gitignore` file, again WHY would I do that, if there's a good reason for that, always do well to provide that and this looks like an optional change hence should have [OPTIONAL] tag.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Let's have more inline comments, example the changes about `.gitignore` could have gone under the `.gitignore` file, Readme file as well.  Using the GitHub inline comments makes CR seamless and easy error tracking and follow up for both CRs and students

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-02 17:04 UTC, acushlakoncept commented on index.html
>      <div id="img-div">
Nice job on the use of polite language to request a change 👍🏽
I think you should also give reasons WHY you're encouraging them to use the semantic HTML element. Also, a little suggestion on what kind of semantic HTML element here would really help, possibly pointers too. This will give the student more insight and conviction on making the requested changes.

2021-06-02 18:54 UTC, tacettinkustu commented on index.html
>      <div id="img-div">
I changed my review in line with your directions.

2021-06-03 00:31 UTC, Spayco approved these changes
Hi @tacettinkustu, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-05 20:04 UTC, merged